# Generated by Django 4.1.6 on 2023-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_createblog_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='img/%y')),
                ('admin_img', models.ImageField(upload_to='img/%y')),
                ('post_img', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
