# Generated by Django 4.1.6 on 2023-09-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='admin_img',
            field=models.ImageField(blank=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='images',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='admin_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='img/%y'),
        ),
    ]
