# Generated by Django 4.1.6 on 2023-09-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_images_admin_img_alter_images_logo_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='admin_img',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='admin_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
