# Generated by Django 4.1.6 on 2023-09-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_images_admin_img_alter_images_logo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='admin_img',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='admin_img'),
        ),
    ]
