# Generated by Django 4.1.6 on 2023-09-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_createblog_admin_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='admin_img',
        ),
    ]
