# Generated by Django 4.1.6 on 2023-09-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_images_admin_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='admin_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
