# Generated by Django 4.1.6 on 2023-09-05 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_createblog_admin_img_images_admin_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='summary',
            field=models.CharField(default=datetime.datetime(2023, 9, 5, 23, 34, 17, 602690, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
