# Generated by Django 4.1.6 on 2023-09-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_createblog_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post_img',
        ),
        migrations.AddField(
            model_name='createblog',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
